title: Buenos días
email: erick.tucto@outlook.com
description: >-
  Este es un sitio web creado para dar mensajes de buenos días.
baseurl: "/yuli" # the subpath of your site, e.g. /blog
url: "https://ericktucto.com/yuli" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: erick_tucto
github_username: ErickTucto

theme: minima
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
